name: Android CI

on:
  push:
    branches: [ "add_flut" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'  # Replace with your desired Flutter version
      - name: Init flutter project set up as a module
        run: |
          flutter config --no-analytics
          cd greenapp
          flutter pub get
          flutter build bundle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
