name: chia_crypto_utils
description: Chia Crypto Utils repository provides an object model for working with Chia primitives serving as a basis for a Chia client.
version: 1.0.15
repository: https://github.com/irulast/chia-crypto-utils

environment:
  sdk: '>=2.15.0 <3.0.0'

scripts:
  integration_tests: 'dart test integration_test/ --concurrency=1'

dependencies:
  args: ^2.3.1
  bech32m: ^0.2.2
  bip39: ^1.0.6
  crypto: ^3.0.1
  get_it: ^7.2.0
  hex: ^0.2.0
  injector: ^2.0.0
  meta: ^1.7.0
  path: ^1.8.1
  quiver: ^3.0.1+1
  yaml: ^3.1.1

dev_dependencies:
  csv: ^5.0.1
  http: ^0.13.4
  lints: ^1.0.0
  rps: ^0.6.3
  test: ^1.19.3
  very_good_analysis: ^2.4.0

false_secrets:
  - /lib/src/networks/chia/mainnet/ssl/private_full_node.key
  - /lib/src/networks/chia/mainnet/ssl/public_full_node.key
  - /lib/src/networks/chia/testnet0/ssl/private_full_node.key
  - /lib/src/networks/chia/testnet0/ssl/public_full_node.key
  - /lib/src/networks/chia/testnet10/ssl/private_full_node.key
  - /lib/src/networks/chia/testnet10/ssl/public_full_node.key